#! /bin/bash

PWD=`pwd`
CURRENTTIME=`date +"%Y%m%d%H%M%S"`
LOG_FILE=$PWD/top_processes_report.$CURRENTTIME.log
touch $LOG_FILE
echo -e "Log Generated by $0 as on $CURRENTTIME" > $LOG_FILE
SLEEP_INTERVAL=20
TOP_PROCESSES=25
while [ 1 -lt 10 ]
do
        CURRENTTIME=`date +"%Y %m-%d %H:%M:%S"`
        echo -e "## Top Processes as on $CURRENTTIME ===============================================" >> $LOG_FILE
        top -b -n 1 | head -$TOP_PROCESSES >> $LOG_FILE
        echo -e "" >> $LOG_FILE
        sleep $SLEEP_INTERVAL
done
